Pull request 1
vanja-veapi/week-2-bonus-grid pull request #1
Opened 2021-09-15 18:03 UTC by vanja-veapi

2021-09-16 10:22 UTC, chomii82 requested changes
Kod je generalno ok. Samo par sitnica da se ispravi.
1. Main content stavi u neki container i daj mu neku max sirinu. Trenutno je previse siroko na velikim ekranima. Pogledaj jos jednom dizajn.
2. Tekst izgleda previse zbijeno, probaj malo da modifikujes line-height. Probaj da ga napravis priblizno prema dizajnu.

2021-09-16 11:34 UTC, vanja-veapi commented
> 
> 
> Kod je generalno ok. Samo par sitnica da se ispravi.
> 
>     1. Main content stavi u neki container i daj mu neku max sirinu. Trenutno je previse siroko na velikim ekranima. Pogledaj jos jednom dizajn.
> 
>     2. Tekst izgleda previse zbijeno, probaj malo da modifikujes line-height. Probaj da ga napravis priblizno prema dizajnu.

Je l' kad kazes Main content, mislis na moju klasu main gde se nalazi ona jedna boldovana recenica?
Jel tekst u mainu izgleda zbijeno ili ovaj donji, posto na donjem(klasa footer) ima line-height 1.4 sto mi je sa slike izgledalo ok

2021-09-17 08:03 UTC, chomii82 approved these changes
Ovo je ok.
Savet za ubuduce, trudi se kada radis sa pixelima da dajes cele brojeve. Na jednom mestu imas border od 2.5px a to moze da izazove bugove.

2021-09-17 09:16 UTC, vanja-veapi commented
> 
> 
> Ovo je ok.
> Savet za ubuduce, trudi se kada radis sa pixelima da dajes cele brojeve. Na jednom mestu imas border od 2.5px a to moze da izazove bugove.

Vazi. Hvala na savetu!

2021-09-17 10:30 UTC, merged